### ISSUE TITLE
Implement sumo_store_elasticsearch:find_by/6

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/sumo_db#107]
To fulfil the remaining **todo** from [this commit](https://github.com/inaka/sumo_db/commit/36522c34b4ae73a7639e64842cc545d81cfe6199)

**Comment by cabol** [comment]
This issue was moved to the specific ElasticSearch adapter repo [HERE](https://github.com/inaka/sumo_db_elasticsearch/issues/6)
