### ISSUE TITLE
Please update tirerl

### ISSUE THREAD

**Issue by essen** [inaka/sumo_db#154]
We're almost there.

https://github.com/inaka/tirerl/issues/25#event-308556162 is done. Now tirerl still needs to be updated here and all will be well in the world.

Sorry I didn't open just one ticket for everything, come to think of it.

**Comment by elbrujohalcon** [comment]
@essen I actually like it this way (with multiple tickets)

**Comment by essen** [comment]
Seems you forgot rebar.config, just saying. Also in tirerl. But maybe that's intentional. :-)

**Comment by elbrujohalcon** [comment]
![facepalm](https://cloud.githubusercontent.com/assets/93657/7709188/97f51f7e-fe31-11e4-9aa6-c133d4acd00b.jpg)

**Comment by essen** [comment]
I get the feeling. I'll see if this can be automated.
