### ISSUE TITLE
Function delete/3 not implemented in postgres store

### ISSUE THREAD

**Issue by Euen** [inaka/sumo_db#163]

**Comment by cabol** [comment]
@Euen I suppose you meant `sumo_store:delete_by/3` right? If so, it is implemented, take a look at it [HERE](https://github.com/inaka/sumo_db_pgsql/blob/master/src/sumo_store_pgsql.erl#L142).

Please confirm and let me know if we can close this issue.

**Comment by Euen** [comment]
Yes, we can close it @cabol, maybe is na old issue.
