### ISSUE TITLE
Typo in sumo_store_mongo

### ISSUE THREAD

**Issue by sergej-klimenko** [inaka/sumo_db#185]
Is there a typo in 
https://github.com/inaka/sumo_db/blob/master/src%2Fsumo_store_mongo.erl#L52 ?

Pool    = sumo_backend_mysql:get_pool(Backend),

Calling sumo_backend_mysql instead of sumo_backend_mongo...

**Comment by elbrujohalcon** [comment]
It is, indeed! :flushed:
