### ISSUE TITLE
Riak Store: implement sort for sumo:find_by/5

### ISSUE THREAD

**Issue by jfacorro** [inaka/sumo_db#200]
It is currently throwing a `not_supported` exception when calling `sumo:find_by/5`.

**Comment by emnvn** [comment]
This problem happened to me, I don't know whether it is the problem of sumo or it is my problem ?

**Comment by jfacorro** [comment]
@emnvn The issue is that support for it has not been implemented yet. The [`sumo_store_riak: find_by /6`](https://github.com/inaka/sumo_db/blob/master/src/sumo_store_riak.erl#L288) function that should handle the `SortFields` just returns a `not_supported` error. So it is a problem casued by anything you did, it is just something that is currently missing :smile:

**Comment by cabol** [comment]
This issue was moved to the specific Riak adapter repo [HERE](https://github.com/inaka/sumo_db_riak/issues/23)
