### ISSUE TITLE
Get riak store to return the number of deleted rows in sumo:delete_by()

### ISSUE THREAD

**Issue by davecaos** [inaka/sumo_db#204]

**Comment by cabol** [comment]
Actually `sumo_store_riak:delete_by/2` is returning the number of deleted docs: https://github.com/inaka/sumo_db/blob/master/src/sumo_store_riak.erl#L129.

So, @elbrujohalcon should we close this issue?

**Comment by elbrujohalcon** [comment]
If there's a test and it is evaluated for the riak store (among others) and it passes,  then yes, @cabol

**Comment by cabol** [comment]
Yes we're testing it, E.g.: https://github.com/inaka/sumo_db/blob/master/test/sumo_basic_SUITE.erl#L132

PD: In fact, thanks to this test we discovered an issue with `sumo_store_mongo:delete_by/2`, which is not returning the total of deleted docs (issue #225). BTW, it was fixed already.

**Comment by elbrujohalcon** [comment]
Ok
