### ISSUE TITLE
Unify sumo_db-riak-extras with sumo_db

### ISSUE THREAD

**Issue by cabol** [inaka/sumo_db#212]
Unify `sumo_db-riak-extras` (https://github.com/inaka/sumo_db-riak-extras) with `sumo_db`.

**Comment by igaray** [comment]
:+1: It's all bollocksed up anyway.

**Comment by elbrujohalcon** [comment]
Basically, all functionality already present in the riak store but in no other store, should be tested in a generic way, so that if at some point someone implements the same functionality for… say… mnesia or elastic_search… they can use the same test suite(s)
