### ISSUE TITLE
Improve sumo in order to have a plugable architecture (separate API from specific implementations)

### ISSUE THREAD

**Issue by cabol** [inaka/sumo_db#221]
At present, `sumo_db` contains not only de API but also all specific backends and stores on the same project. The idea is to separate the API from the implementations and keep them in separated projects. The only adapter contained in sumo should be `mnesia`, since it is native and we don't need any external dependency.

- [x] Create one project for each adapter: `sumo_db_pgsql`, `sumo_db_mysql`, `sumo_db_riak`, `sumo_db_elasticsearch` and `sumo_db_mongo`.
- [x] Take out all specific backends and stores of `sumo_db`, except `mnesia`.
- [x] Fix build files in `sumo_db`, and make sure that tests run OK.
- [x] Copy the corresponding files (backend and store) to each project, and then do the necessary fixes to make it work.
- [ ] Each project MUST be well documented, not only `sumo_db` but also each adapter project.

**Comment by elbrujohalcon** [comment]
They're evolving independently now… I think we can close this one.
