### ISSUE TITLE
Fix find_by functions in Riak Store to work with different data types, not only binaries.

### ISSUE THREAD

**Issue by cabol** [inaka/sumo_db#222]
Currently, due to Riak store works with binaries inside, the `find_by/5` function doesn't works well with values different than binaries in the conditions.

E.g.: if you have an integer field in your model, and you want to find all results that match with that field:

```
sumo:find_by(my_model, [{age, <<"10">>}]).
```

The idea is modify `sumo_store_riak` to allow work with different data types, as defined in the schema, E.g:

```
sumo:find_by(my_model, [{age, 10}]).
```

**Comment by harenson** [comment]
Already fixed.
