### ISSUE TITLE
Add fix to README.md for MongoDB-CR authentication failure

### ISSUE THREAD

**Issue by harenson** [inaka/sumo_db#224]
Go to mongoDB console and delete your current user & set authSchema version to 3 instead of 5 , follow these commands in mongo console -
```
mongo
use admin
db.system.users.remove({})    <== removing all users
db.system.version.remove({}) <== removing current version 
db.system.version.insert({ "_id" : "authSchema", "currentVersion" : 3 })
```
Now restart the mongod and create new user then it should work fine.

**Note**: use remove commands in test db only, if in production use update.

Fix taken from: http://stackoverflow.com/a/31476552

**Comment by cabol** [comment]
This issue was fixed in PR: https://github.com/inaka/sumo_db/pull/227

**Comment by harenson** [comment]
Closed in https://github.com/inaka/sumo_db_mongo/pull/3
