### ISSUE TITLE
Modify events config to follow the same form as docs

### ISSUE THREAD

**Issue by Euen** [inaka/sumo_db#268]
Replace `{model, event_manager_module}` instead of `{doc_module, event_manager_module}`

**Comment by cabol** [comment]
@Euen (/cc @elbrujohalcon) I think we support this already, we actually are handling the event in that way `{model, event_manager_module}`, check this out: https://github.com/inaka/sumo_db/blob/master/src/sumo_config.erl#L47

As you can see, the event config is defined as `{DocName :: atom(), EventHandler :: module()}`, where the `DocName` is the name of the model.

What do you guys think?

**Comment by elbrujohalcon** [comment]
@cabol I'm not sure… I think @Euen and I needed to use the module in our config files for this to work. Are you sure it works, despite of that spec?

And yes… you can use `sumo:schema_name()` there, I'm cool with that.
