### ISSUE TITLE
docs sys.config

### ISSUE THREAD

**Issue by qibinlin** [inaka/sumo_db#335]
There is a project to use sumo_db, docs have more than 2,000, I must in sys. config file, {docs, {PURCHLINE', my_store_pgsql, {{module => purchLine}

', {'INVENTDIM', my_store_pgsql, {{module => inventDim},... ]

Specify more than 2,000 docs

Is there any other way?

**Comment by elbrujohalcon** [comment]
Let me see if I understand your question.
I think you have a project with more than 2000 different models/docs.
Currently, `sumo_db` requires you to put them in the app environment and you use `sys.config` to manage that environment.
You're asking if there is a different way to specify the models that doesn't require you to manually type in 2000 different docs in a text file.

The answer is… well… _kind of?_. You see… SumoDB configuration is basically just OTP configuration. So, you can set that `docs` property using any of the available methods to set OTP configuration:

- You can use `sys.config` and build a release (as you are probably doing).
- You can include a line like `"/path/to/my.docs.config"` within `sys.config` pointing to another file where only sumo_db config (or only the docs) is. That file can then be dynamically generated.
- You can use command line arguments in `vm.args` like `-sumo_db docs $(generate_docs)` where `generate_docs` is a bash script that generates the doc descriptions for you.
- You can use `set_env` as in the following code where `generate_docs/0` is an erlang function that generates the doc descriptions for you…

```erlang
…
ok = application:load(sumo_db),
ok = application:set_env(sumo_db, docs, generate_docs()),
…
```

For more information, check out [the OTP docs](http://erlang.org/doc/design_principles/applications.html#configuring-an-application).

**Comment by qibinlin** [comment]
Your reply. It solved my problem. Thanks very much。
